2025-01-16 10:50:45,857 INFO    MainThread:106265 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2025-01-16 10:50:45,857 INFO    MainThread:106265 [wandb_setup.py:_flush():76] Configure stats pid to 106265
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_setup.py:_flush():76] Loading settings from /user/ma4177/.config/wandb/settings
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_setup.py:_flush():76] Loading settings from /user/ma4177/Exp_neural/wandb/settings
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'testing.py', 'program_abspath': '/user/ma4177/Exp_neural/testing.py', 'program': '/user/ma4177/Exp_neural/testing.py'}
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_init.py:_log_setup():521] Logging user logs to /user/ma4177/Exp_neural/wandb/run-20250116_105045-nmxh4vyh/logs/debug.log
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_init.py:_log_setup():522] Logging internal logs to /user/ma4177/Exp_neural/wandb/run-20250116_105045-nmxh4vyh/logs/debug-internal.log
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_init.py:init():561] calling init triggers
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_init.py:init():611] starting backend
2025-01-16 10:50:45,858 INFO    MainThread:106265 [wandb_init.py:init():615] setting up manager
2025-01-16 10:50:45,859 INFO    MainThread:106265 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-16 10:50:45,862 INFO    MainThread:106265 [wandb_init.py:init():623] backend started and connected
2025-01-16 10:50:45,864 INFO    MainThread:106265 [wandb_init.py:init():715] updated telemetry
2025-01-16 10:50:45,880 INFO    MainThread:106265 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2025-01-16 10:50:45,976 ERROR   MainThread:106265 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-01-16 10:50:46,017 ERROR   MainThread:106265 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/user/ma4177/.conda/envs/exp_neural/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/user/ma4177/.conda/envs/exp_neural/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-01-16 10:50:47,019 WARNING MsgRouterThr:106265 [router.py:message_loop():77] message_loop has been closed
